### PR TITLE
feat: add `renamePaths` action

### PR DESCRIPTION
**Pull request by jrson83**
### Description

This PR adds a `renamePaths` action to rename files or directories inside the target directory.

- [x] I implemented the action
- [x] I added tests to cover functionality
- [x] I made changes to the docs

### Motivation

When hosting presets in a multi mono-repository, I find no way to disable VSCode TypeScript IntelliSense for the entire presets package/folder in the workspace. When maintaining the presets the missing import errors are kind of annoying.

### Solution

For `.ts,tsx` files I came up with the solution adding `// @ts-nocheck` to the top off the template files, which I then remove with `editFiles` action after extrating the templates. Since this is not possible for `tsconfig.json` files, with the `renamePaths` action, it is possible to name the hosted file `_tsconfig.json` (so the IDE does not pick it up) and rename it after extracting the templates.

---

I did not use `path.parse`, but instead created a custom function to return the `parsedPath`.
I did not find any required formatter rules for this repository, other then ESLint. If you want a different formatting or if there is something to optimize let me know.

### CODE REVIEW

**Comment by jrson83** [comment]
Seems like vite version is breaking the deploy action. When running `lint` I also got an error, but I didn't touch this.

```bash
D:\_projects\preset\preset\packages\core\src\context.ts
  4:8  warning  Using exported name 'simpleGit' as identifier for default export  import/no-named-as-default

✖ 1 problem (0 errors, 1 warning)
```

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
Looks awesome. Great PR. 👍 

I'm afraid the docs won't be updated even after I merge, they seem to be broken even after an upgrade to latest VitePress.

**Comment by jrson83** [comment]
Thanks! Maybe updating the github action helps?

**Comment by innocenzi** [comment]
It's related to VitePress and not the GitHub actions, but you're right, I'll also update them 👍

**Pull request merged**
