### PR TITLE
feat(actions): select prompt

### PR DESCRIPTION
**Pull request by ghost**
Adds select style prompt to allow choices to be navigated by keyboard...

Screenshot 2023-02-21 at 16 21 28
Screenshot 2023-02-21 at 16 21 41
Screenshot 2023-02-21 at 16 22 30

### CODE REVIEW

**Comment by innocenzi** [comment]
Hey, thanks for your contribution! I've tried using a select prompt but I got the text prompt instead. I wanted to debug why and when looking at `list.ts` I saw that the code was not typed which makes it super hard to review. It also seems like some code is not used at all (pagination).

Could you please type the code and ensure all of it is actually used?

**Comment by innocenzi** [comment]
Sorry for the force pushes, I added type-checking in CI and rebased this branch

**Comment by ghost** [comment]
@innocenzi I have an additional commit adding tests for the input/select renderers. Not sure if I should add them to this PR as a separate one might be better to check if its the sort of direction you would be happy with.

**Comment by innocenzi** [comment]
Just a heads up I haven't forgotten about this PR, I have a lot of work right now but I'll review as soon as I find time!

**Comment by innocenzi** [comment]
Thank you!

**Comment by jrson83** [comment]
Awesome, I was working on a PR for similar select prompt, but stopped working on it since I couldnt get it working right.

**Pull request merged**
